# Site settings
title: "Thích học toán"
email: 
description: "Blog toán học"
baseurl: ""
url: ""
title_description: "Blog chia sẻ các kiến thức toán cơ bản"
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics:
disqus_account: 
github_repository: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Thích học toán"
footer_right: "Made by Thích học toán"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
