# Site settings
title: "Nikola Tesla"
email: 
description: "Một kĩ sư đam mê toán học"
baseurl: ""
url:
title_description: "Tôi là một nhà phát minh, nhà vật lý, kỹ sư cơ khí và kỹ sư điện, có niềm đam mê đặc biệt với toán học. "
title_image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/N.Tesla.JPG"
google_analytics: ""
disqus_account: 
github_repository: 
addthis_id: 
post_limit: 7

# Social usernames/URLs
twitter_username: 
github_username:  
linkedin_link: 
google_plus_link: 
stackoverflow_link:

# Footer
footer_left:
footer_right:

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
